services:
  - type: web
    name: amg-fitness-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn AmGFitness.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.10.12"
