# Generated by Django 4.2.3 on 2023-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
