# Generated by Django 4.2.3 on 2023-07-17 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_membershipplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(max_length=55),
        ),
    ]
